jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

upload:
  solved:
    path: C:\Dev\nor3st-backend\src\main\resources\static\upload\solved\
  problem:
    path: C:\Dev\nor3st-backend\src\main\resources\static\upload\problems\

ai:
  url: http://221.163.19.218:5541

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# Include external database configuration
spring.config.import: db-config.yml